# Cranium Charades - Subdomain routing
cranium-charades.doughughes.net {
    reverse_proxy localhost:8004

    handle_errors {
        @401 expression {http.error.status_code} == 401
        redir @401 https://www.doughughes.net/login 302
    }
}
